#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox"
STYLE="cus2-bst"
RASI="$DIR/themes/$STYLE/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
