#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch kitty with bspwm config

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/kitty/kitty.toml"

if [ "$1" == "--float" ]; then
	kitty --class 'kitty-float,kitty-float' --config-file "$CONFIG"
elif [ "$1" == "--full" ]; then
	kitty --class 'kitty-fullscreen,kitty-fullscreen' --config-file "$CONFIG" \
			  -o window.startup_mode="'Fullscreen'" \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
else
	kitty --config-file "$CONFIG" ${@}
fi
